name: test-py39-functional-microshift

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHONWARNINGS: ignore
  KUBECONFIG: ${{ github.workspace }}/kubeconfig
  ACCT_MGT_VERSION: "44f8f13e4d876249ed2ee1a77fbac86dfd8b3960"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Fix for "grup-efi-amd64-signed" missing
        run: |
          sudo apt-mark hold grub-efi-amd64-signed

      - name: Upgrade and install packages
        run: |
          bash ./ci/setup-ubuntu.sh

      - name: Install oc/kubectl clients
        run: |
          bash ./ci/setup-oc-client.sh

      - name: Install Microshift
        run: |
          ./ci/microshift.sh

      - name: Install ColdFront and plugin
        run: |
          ./ci/setup.sh

      - name: Run functional tests
        run: |
          echo Hello test
          curl -u admin:pass https://onboarding-onboarding.cluster.local/users/admin -k
